### ISSUE TITLE
Problem with core-js

### ISSUE THREAD

**Issue by 3257** [cheton/github-release-cli#23]
Hey, there,

I got an error when using the tool with an iOS build through buddybuild. This is it:

`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

It started happening today. Tried to manually update the core-js dependency to over version 3 but the issue persists.

**Comment by 3257** [comment]
2020-09-21T11:18:28.826Z - ce:     npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

2020-09-21T11:18:31.076Z - ci:     /usr/local/bin/github-release -> /usr/local/lib/node_modules/github-release-cli/bin/github-release

2020-09-21T11:18:31.101Z - ci:     > core-js@2.6.11 postinstall /usr/local/lib/node_modules/github-release-cli/node_modules/core-js

2020-09-21T11:18:31.103Z - ci:     > node -e "try{require('./postinstall')}catch(e){}"

2020-09-21T11:18:31.175Z - ci:     Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

2020-09-21T11:18:31.176Z - ci:     The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 

2020-09-21T11:18:31.178Z - ci:     > https://opencollective.com/core-js 

2020-09-21T11:18:31.178Z - ci:     > https://www.patreon.com/zloirock 

2020-09-21T11:18:31.180Z - ci:     Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

2020-09-21T11:18:31.195Z - ci:     + github-release-cli@2.0.0

2020-09-21T11:18:31.196Z - ci:     added 56 packages from 97 contributors in 4.005s

2020-09-21T11:18:31.326Z - ce:     internal/modules/cjs/loader.js:797

2020-09-21T11:18:31.327Z - ce:         throw err;

2020-09-21T11:18:31.330Z - ce:         ^

2020-09-21T11:18:31.330Z - ce:     Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'

2020-09-21T11:18:31.332Z - ce:     Require stack:

2020-09-21T11:18:31.332Z - ce:     - /usr/local/lib/node_modules/github-release-cli/lib/index.js

2020-09-21T11:18:31.334Z - ce:     - /usr/local/lib/node_modules/github-release-cli/bin/github-release

2020-09-21T11:18:31.335Z - ce:         at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)

2020-09-21T11:18:31.337Z - ce:         at Function.Module._load (internal/modules/cjs/loader.js:687:27)

2020-09-21T11:18:31.338Z - ce:         at Module.require (internal/modules/cjs/loader.js:849:19)

2020-09-21T11:18:31.340Z - ce:         at require (internal/modules/cjs/helpers.js:74:18)

2020-09-21T11:18:31.341Z - ce:         at Object.<anonymous> (/usr/local/lib/node_modules/github-release-cli/lib/index.js:3:31)

2020-09-21T11:18:31.342Z - ce:         at Module._compile (internal/modules/cjs/loader.js:956:30)

2020-09-21T11:18:31.344Z - ce:         at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)

2020-09-21T11:18:31.345Z - ce:         at Module.load (internal/modules/cjs/loader.js:812:32)

2020-09-21T11:18:31.347Z - ce:         at Function.Module._load (internal/modules/cjs/loader.js:724:14)

2020-09-21T11:18:31.348Z - ce:         at Module.require (internal/modules/cjs/loader.js:849:19) {

2020-09-21T11:18:31.350Z - ce:       code: 'MODULE_NOT_FOUND',

2020-09-21T11:18:31.352Z - ce:       requireStack: [

2020-09-21T11:18:31.353Z - ce:         '/usr/local/lib/node_modules/github-release-cli/lib/index.js',

2020-09-21T11:18:31.354Z - ce:         '/usr/local/lib/node_modules/github-release-cli/bin/github-release'

2020-09-21T11:18:31.355Z - ce:       ]

2020-09-21T11:18:31.357Z - ce:     }

**Comment by theimpulson** [comment]
I have similar issues on uploading files:

```
theimpulson@packet:~/los/out/target/product/begonia$ github-release upload --owner HyperTeam --repo android_device_redmi_begonia --tag "20200922" --name "lineage-17.1-20200922-UNOFFICIAL" lineage-17.1-2020*-UNOFFICIAL-*.zip lineage-17.1-2020*-UNOFFICIAL-*.zip.md5sum recovery.img 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-release-cli/lib/index.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by a-tokyo** [comment]
+1

```
+ github-release-cli@2.0.0
added 56 packages from 97 contributors in 2.349s
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
Require stack:
- /usr/local/lib/node_modules/github-release-cli/lib/index.js
- /usr/local/lib/node_modules/github-release-cli/bin/github-release
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-release-cli/lib/index.js:3:31)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/github-release-cli/lib/index.js',
    '/usr/local/lib/node_modules/github-release-cli/bin/github-release'
  ]
}
```

**Comment by MurakamiShinyu** [comment]
+1

```
$ npm install -g github-release-cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
...

$ github-release -V
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
...
```

I found that `npm install @babel/runtime` solves the error:

```
$ npm install -g @babel/runtime
+ @babel/runtime@7.11.2
added 2 packages from 2 contributors in 0.815s

$ github-release -V
2.0.0
```

It seems the `"babel-runtime": "^6.26.0"` in the package.json causes the problem:

https://github.com/cheton/github-release-cli/blob/236dd503e03fb676e6c0e3ddf894c3b20c125a91/package.json#L33

Perhaps this should be updated to `"@babel/runtime": "^7.11.2"`?
